config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root to: 'home#index'
  get 'home/index'
  get 'terms' => 'pages#terms'
  get 'about' => 'pages#about'

  resource :contacts, only: %i[new create], path_names: { new: '' }
  resources :articles do
    resources :comments
  end

  namespace :api do
    namespace :v1 do
      resources :articles, only: %i[index show create update destroy], defaults: {format: :json}
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  has_many :comments, dependent: :destroy
  belongs_to :user
  validates :title, presence: true
  validates :text, presence: true
  paginates_per 5
  def subject
    title
  end

  def last_comment
    comments.last
  end
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user
  validates :body, presence: true, length: { maximum: 250 }
end

app/models/contact.rb
# frozen_string_literal: true

class Contact < ApplicationRecord
  validates :email, presence: true
  validates :message, presence: true
end

app/models/log.rb
class Log < ApplicationRecord
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :articles
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/api/v1/articles_controller.rb
class Api::V1::ArticlesController < ApplicationController
    before_action :authenticate_user!, only: %i[new create edit update destroy]
    before_action :is_author?, only: %i[edit update destroy]

    def index
      @articles = Article.order(:created_at).page params[:page]
      respond_to do |format|
        format.json
        format.xml do
          render index: @articles
        end
        format.pdf do
          render pdf: "List of #{@articles.count} articles", template: "articles/list_of_articles", formats: [:html]
        end
      end
    end

    def new
      @article = Article.new
    end

    def show
      @article = Article.find(params[:id])
      respond_to do |format|
        format.json
        format.xml do
          render show: @article
        end
        format.pdf do
          render pdf: "Article id: #{@article.id}", template: "articles/article", formats: [:html]
        end
      end
    end

    def create
      @article = Article.new(article_params)
      @article.user = current_user
      if @article.valid?
        @article.save
        redirect_to @article
      else
        render action: 'new'
      end
    end

    def edit
      @article = Article.find(params[:id])
    end

    def update
      @article = Article.find(params[:id]) # получаем саму статью

      if @article.valid?
        @article.update(article_params)
        flash[:success] = 'Article was updated'
        redirect_to @article
      else
        flash[:success] = 'Article was not updated'
        render action: 'edit'
      end
    end

    def destroy
      @article = Article.find(params[:id])
      @article.destroy
      redirect_to articles_path
    end

    def is_author?
      @article = Article.find(params[:id])
      redirect_to articles_path unless @article.user_id == current_user.id
    end

    private

    def article_params
      params.require(:article).permit(:title, :text)
    end
  end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  before_action :authenticate_user!, only: %i[new create edit update destroy]
  before_action :is_author?, only: %i[edit update destroy]

  def index
    @articles = Article.order(:created_at).page params[:page]
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "List of #{@articles.count} articles", template: "articles/list_of_articles", formats: [:html]
      end
    end
  end

  def new
    @article = Article.new
  end

  def show
     @article = Article.find(params[:id])
       respond_to do |format|
            format.html
            format.pdf do
              render pdf: "Article id: #{@article.id}", template: "articles/article", formats: [:html]
            end
       end
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.valid?
      @article.save
      redirect_to @article
    else
      render action: 'new'
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id]) # получаем саму статью

    if @article.valid?
      @article.update(article_params)
      flash[:success] = 'Article was updated'
      redirect_to @article
    else
      flash[:success] = 'Article was not updated'
      render action: 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  def is_author?
    @article = Article.find(params[:id])
    redirect_to articles_path unless @article.user_id == current_user.id
  end

  private

  def article_params
    params.require(:article).permit(:title, :text)
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:create]
  def create
    @article = Article.find(params[:article_id])
    comment = @article.comments.create(comment_params)
    comment.user = current_user
    comment.author = current_user.username
    comment.save
    redirect_to articles_path(@article)
  end

  private

  def comment_params
    params.require(:comment).permit(:author, :body)
  end
end

app/controllers/contacts_controller.rb
# frozen_string_literal: true

class ContactsController < ApplicationController
  def new; end

  def create
    @contact = Contact.new(contact_params)
    if @contact.valid?
      @contact.save
    else
      render action: 'new'
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:email, :message)
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def about; end

  def terms; end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @query = Article.ransack(params[:q])
    @articles =  @query.result(distinct: true)
  end
end

app/helpers/api/v1/articles_helper.rb
module ApiArticleHelper
end

app/helpers/api_article_helper.rb
module ApiArticleHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/articles_helper.rb
# frozen_string_literal: true

module ArticlesHelper
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/helpers/contacts_helper.rb
# frozen_string_literal: true

module ContactsHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>
<div class="row">
 <div class="col-xs-12">
  <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
  <div class="form-group">
   <div class="control-label col-sm-2">
    <%= f.label :title %>
   </div>
   <div class="col-sm-6">
    <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
   </div>
  </div>
  <div class="form-group">
   <div class="control-label col-sm-2">
    <%= f.label :description %>
   </div>
   <div class="col-sm-6">
    <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of article" %>
   </div>
  </div>
  <div class="form-group">
   <div class="col-sm-offset-2 col-sm-10">
    <%= f.submit class: 'btn btn-primary btn-large' %>
   </div>
  </div>
<% end %>
 </div>
</div>

app/views/articles/article.html.erb
PDF generation date:
<%= Time.zone.now %>
<p>
  <strong>Article ID:</strong>
  <%=  @article.id %>
</p>
<p>
  <strong>Article title:</strong>
  <%=  @article.title %>
</p>
<p>
  <strong>Content:</strong>
  <%=  simple_format(@article.text) %>
</p>

<strong> Comments: </strong>
<h3><%= 'No Comments' if @article.comments.empty? %></h2>
  <div class="card-group">
    <% @article.comments.each do |comment| %>
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Comment by <%= comment.author %></h5>
          <p class="card-text"><%= comment.body %></p>
        </div>
      </div>
    <% end %>
  </div>

app/views/articles/create.html.erb
<h1> Thanks for posting new article! </h1>

<%= link_to 'Show all articles', articles_path %>

app/views/articles/edit.html.erb
<div class="container">
    <div class="small-box mx-auto text-center">
<h1>Edit article! </h1>

<%= link_to 'Back', articles_path %>
<% if @article.errors.any? %>
 <h2>The following errors prevented the article from saving:</h2>
 <ul>
 <% @article.errors.full_messages.each do |msg|%>
 <li><%= msg %></li>
 <% end %>
 </ul>
<% end %>
<%= form_for :article, url: article_path(@article), method: :put, data: {turbo:false} do |f| %>
   <p>
      <%= f.label :title %> <br />
      <%= f.text_field :title %>
   </p>

   <p>
      <%= f.label :text %> <br />
      <%= f.text_area :text %>
   </p>

 <p>
  <%= f.submit %>
 </p>

<% end %>
</div>
</div>

app/views/articles/index.html.erb
<h1 align="center">List of articles</h1>
<% @articles.each do |article| %>
<div class="card">
  <div class="card-header">
   <div class="fw-semibold">
     <%= link_to article.title, article_path(article) %>
   </div>
  </div>
  <div class="card-body">
    <blockquote class="blockquote mb-0">
      <p> <%= truncate(article.text, length: 100) %></p>
      <footer class="blockquote-footer">Posted by <cite title="Source Title"><%= article.user.username %></cite></footer>
    </blockquote>
    <div class="btn-group" role="group" aria-label="Basic mixed styles example">
      <%= button_to "PDF", article_path(article, format: :pdf), method: :get, class: "btn btn-xs btn-outline-secondary" %>&nbsp;
      <%= button_to "Edit", edit_article_path(article),method: :get, class: "btn btn-xs btn-primary" %>&nbsp;
      <%= button_to "Delete", article_path(article), method: :delete, data: { confirm: "Are you sure you want to delete this article?"}, class: "btn btn-xs btn-danger" %>
    </div>
  </div>
</div>
<% end %>
</br>
<div align="center">
<%= paginate @articles, window: 2%>
</div>
</br>

app/views/articles/list_of_articles.html.erb
PDF generation date:
<%= Time.zone.now %>

<h1 align="center">List of articles</h1>
<% @articles.each do |article| %>
  <div class="card">
    <div class="card-header">
      <div class="fw-semibold">
        <strong>Article Title:</strong>
        <%= link_to article.title, article_path(article) %>
      </div>
    </div>
    <div class="card-body">
      <blockquote class="blockquote mb-0">
        <strong>Article Content:</strong>
        <p> <%= truncate(article.text, length: 100) %></p>
        <footer class="blockquote-footer">Posted by <cite title="Source Title"><%= article.user.username %></cite></footer>
      </blockquote>
    </div>
  </div>
<% end %>
</br>
<div align="center">
  <%= paginate @articles, window: 2%>
</div>
</br>

app/views/articles/new.html.erb
<%= link_to 'Back', articles_path %>
<%= form_for :article, url: articles_path, data: {turbo:false} do |f| %>
<div class="container">
    <div class="small-box mx-auto text-center">
 <h1>Make new article! </h1>

   <p>
      <%= f.label :title %> <br />
      <%= f.text_field :title %>
   </p>
   <p>
      <%= f.label :text %> <br />
      <%= f.text_area :text %>
   </p>
   <p>
      <%= f.submit %>
   </p>



 </div>
</div>
  <% end %>

<% if @article.errors.any? %>
<div class="container">
    <div class="small-box mx-auto text-left">
 <h2>The following errors prevented the article from saving:</h2>
 <ul>
 <% @article.errors.full_messages.each do |msg|%>
 <li><%= msg %></li>
 <% end %>
 </ul>
<% end %>
</div>
</div>

app/views/articles/show.html.erb
<%= link_to 'Back', articles_path %>

<%= link_to "Edit", edit_article_path(@article) %>
<div class="container">
    <div class="small-box mx-auto text-center">

<div class="card">
  <div class="card-header">
     <h4><strong> Showing selected article</strong></h4>

  </div>
  <div class="card-body">
    <h5 class="card-title"><%= @article.title %></h5>
    <p class="card-text"><%= @article.text %></p>
   </div>
</div>
</br>
</br>
</br>


   <h2> Comments: </h2>
  <h3><%= 'No Comments' if @article.comments.empty? %></h2>
<div class="card-group">
    <% @article.comments.each do |comment| %>
   <div class="card">


       <div class="card-body">
      <h5 class="card-title">Comment by <%= comment.author %></h5>
      <p class="card-text"><%= comment.body %></p>

    </div>

  </div>
 <% end %>
  </div>




</br>
</br>
</br>



<div class="card">





<h2> Add comment </h2>

<p>
<%= form_for([@article, @article.comments.build]) do |f| %>

   <p>
      <%= f.label :body %> <br />
      <%= f.text_area :body %>
   </p>

 <p>
  <%= f.submit %>
 </p>

<% end %>

</p>

</div>

app/views/contacts/create.html.erb
<h1> Thanks! </h1>

app/views/contacts/new.html.erb
<h1> Contact us! </h1>

<%= form_for :contact, url: contacts_path, data: {turbo:false} do |f| %>
   <% if @contact && @contact.errors.any? %>
   <p>
      <ul>
         <% @contact.errors.full_messages.each do |msg| %>
         <li> <%= msg %> </li>
          <% end %>
       </ul>

   </p>
    <% end %>
<p>
      <%= f.label :email %> <br />
      <%= f.text_field :email %>
</p>

<p>
      <%= f.label :message %> <br />
      <%= f.text_area :message %>
</p>

<p>
   <%= f.submit 'Send message' %>

</p>

<% end %>